baseURL: "https://franzideckstein.github.io/"
title: Franziska Deckstein
paginate: 20
theme: PaperMod
disableKinds:
  - rss

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
  tag: tags

menu:
  main:
    - name: Research
      pageRef: /research
      weight: 2
    - name: CV
      pageRef: /cv
      weight: 3

params:
  description: "I am a Research Assistant and PhD Student at the Chair of Public Economics at Leipzig University."
  author: Franziska Deckstein
  DateFormat: "02 Jan 2006"
  defaultTheme: light
  hideFooter: false
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: false
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true

  profileMode:
    enabled: true
    title: Franziska Deckstein
    subtitle: "I'm a Research Assistant and PhD Student at the Chair of Public Economics at Leipzig University. My interests lie in the fields of Public Economics, Labor Economics, and Inequality."
    imageUrl: "portrait2.jpg"
    imageWidth: 200
    imageHeight: 200
    imageTitle: Franziska Deckstein
    buttons:
      - name: Research
        url: /research/
      - name: CV
        url: /cv/

  socialIcons:
    - name: Twitter
      url: https://bsky.app/profile/franzideckstein.bsky.social
    - name: LinkedIn
      url: https://www.linkedin.com/in/franziska-deckstein-15598015b/
    - name: GitHub
      url: https://github.com/franzideckstein
    - name: Email
      url: mailto:franziska.deckstein@uni-leipzig.de

  assets:
    disableHLJS: true
    disableScrollBarStyle: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    mask_icon: "/safari-pinned-tab.svg"

  cover:
    hiddenInList: false
    hiddenInSingle: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2